# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

In [3]:
# Answer here
import numpy as np

a = np.arange(12).reshape(4, 3)
b = np.arange(3).reshape(1, 3)



print(a+b)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [13]:
# Answer here
a= np.array([1,2,3,4,5])
print("reduce function: " ,np.add.reduce(a))

print("accomulate: ",np.add.accumulate(a))

reduce function:  15
accomulate:  [ 1  3  6 10 15]


### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [23]:
# Answer here
row1= np.arange(10,80,5)
row2= np.arange(5,47,3)

array = np.array([row1,row2])

print(array)


[[10 15 20 25 30 35 40 45 50 55 60 65 70 75]
 [ 5  8 11 14 17 20 23 26 29 32 35 38 41 44]]


### Now use indexing to select the 5th 7th and 11th columns

In [37]:
# Answer here
print("values: ", array[:,[4,6,10]])

values:  [[30 40 60]
 [17 23 35]]


### Select the 2nd row and fourth-last to second-last columns

In [43]:
#Answer here
print(array[1: ,10:13])

[[35 38 41]]


### Select 3rd to 3rd last columns skipping every second column

In [53]:
# Answer here
print(array[:, 2:-2:2])

[[20 30 40 50 60]
 [11 17 23 29 35]]


###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [61]:
# Answer here
print(array[:, -3:2:-2])

[[65 55 45 35 25]
 [38 32 26 20 14]]


### We will work with the following array:

In [7]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Use slicing only to select 3rd and last row along with 2nd and last columns

In [81]:
# Answer here
print(a[2::2, 1::3])

[[11 14]
 [21 24]]


### Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [93]:
# Answer here
b=a[::2, [2,3]]
print(b)


[[ 2  3]
 [12 13]
 [22 23]]


### Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [109]:
# Answer here
b=a[1:, 1::2]

b=b[[0,2,3]]
print(b)

[[ 6  8]
 [16 18]
 [21 23]]


### Change the values 1, 10, 19 and 22 in the array to -2

In [202]:
# Answer
indices = [(0, 1), (2, 0), (3, 4), (4, 2)]
for row, col in indices:
    a[row, col] = -2

print(a)

[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]


### Repeat above using boolean indexing

In [156]:
# Answer here
mask=np.array([[0,1,0,0,0],
              [0,0,0,0,0],
              [1,0,0,0,0],
              [0,0,0,0,1],
              [0,0,1,0,0]],dtype=bool)
a[mask]=-2

print(a)

[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]


### Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [7]:
# Answer here
a = np.arange(25).reshape(5, 5)

b=a[:,::3]
mask=np.array([
    [1,1],
    [0,0],
    [1,1],
    [1,1],
    [0,0]],dtype=bool)
b=b[mask]
print(b)


[ 0  3 10 13 15 18]


### Calculating the sum, min and max of all diagonal values

In [21]:
# Answer here
mask=np.array([[1,0,0,0,1],
              [0,1,0,1,0],
              [0,0,1,0,0],
              [0,1,0,1,0],
              [1,0,0,0,1]],dtype=bool)
b=a[mask]

min=b.min()
max=b.max()
sum=b.sum()

print("array: ",b)
print("minimum: ",min)
print("maximum: ",max)
print("sum: ",sum)

array:  [ 0  4  6  8 12 16 18 20 24]
minimum:  0
maximum:  24
sum:  108


### Calculate the sum of differences between the 2nd row and 2nd last column

In [176]:
# Answer here
b=np.subtract(a[1, :],a[:, 3])
print("subtract of row and column: ",b)
print("\nsum: ", b.sum())

subtract of row and column:  [  2  -2  -6 -10 -14]

sum:  -30


### Create a new array that is the sum of even rows and odd rows

In [200]:
# Answer here
array=np.array([np.sum(a[::2,:]),np.sum(a[1::2,:])])
print("array: ",array)

array:  [180 120]


## You are done. Good job!